[privacy]
enable_tracker_blocking = false
enable_do_not_track = true
disable_component_update = true
disable_default_apps = true
disable_sync = true
disable_suggestions = true
disable_personal_autofill = true
block_third_party_cookies = true
no_referrer = true
force_https = true
disable_features = [
    "Preload",
    "PrefetchPrivacyChanges",
    "NetworkService",
]
default_search_engine = "https://duckduckgo.com"
